### ISSUE TITLE
Segfault in HMatrix<T>::assemble with 1x1 matrices

### ISSUE THREAD

**Issue by dbarbier** [jeromerobert/hmat-oss#16]
Currently `data.isAdmissibleLeaf()` returns true, because diameter is null.  And more generally, we must add checks to ensure that bounding boxes are defined (ie clusters have at least 2 points) and diameter is not null (ie points are not coincident).

**Comment by jeromerobert** [comment]
"points are not coincident" is currently not checked.

**Comment by dbarbier** [comment]
It should be fixed now
