### ISSUE TITLE
version from tarball

### ISSUE THREAD

**Issue by jschueller** [jeromerobert/hmat-oss#23]
when compiling outside of git, ie from a tarball,
"git describe --dirty=-dirty --always --tags" returns "3627653-dirty"
maybe the "--always" part should be dropped and the error code checked to fall back to the default number version (as the first argument passed to git_version)
git version 2.1.3

**Comment by jschueller** [comment]
great, thanks!
could we get a new tag ?

**Comment by jeromerobert** [comment]
1.0.4 tagged.
