### ISSUE TITLE
cmake warning regarding CMP0018

### ISSUE THREAD

**Issue by jschueller** [jeromerobert/hmat-oss#27]
CMake Warning (dev) in CMakeLists.txt:
  Variable CMAKE_SHARED_LIBRARY_CXX_FLAGS has been modified.  CMake will
  ignore the POSITION_INDEPENDENT_CODE target property for shared libraries
  and will use the CMAKE_SHARED_LIBRARY_CXX_FLAGS variable instead.  This may
  cause errors if the original content of CMAKE_SHARED_LIBRARY_CXX_FLAGS was
  removed.

  Policy CMP0018 is not set: Ignore CMAKE_SHARED_LIBRARY_<Lang>_FLAGS
  variable.  Run "cmake --help-policy CMP0018" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done

see http://www.cmake.org/cmake/help/v3.0/policy/CMP0018.html

**Comment by jeromerobert** [comment]
This was added by 1af23a0 (i.e. you ;-) ). Do you remember why ? Should we just add a if(MINGW) around line 105 ? Or may be a better fix for the mingw problem could be found ?
