### ISSUE TITLE
Sort algorithm with groups

### ISSUE THREAD

**Issue by gsylvand** [jeromerobert/hmat-oss#57]
https://github.com/jeromerobert/hmat-oss/blob/9ced6843c7fb0746b2cdd9f9ff3bae375bf90052/src/clustering.cpp#L50-L54

If I understand correctly, when we use group index, we don't sort at all on coordinates : no matter what is the value of `axis_`, we sort only on the group index. Is this correct ? Is this what we expect ?

**Comment by dbarbier** [comment]
Yes and yes; closing since everything looks good.
