### ISSUE TITLE
 error: use of undeclared identifier 'openblas_set_num_threads'

### ISSUE THREAD

**Issue by yurivict** [jeromerobert/hmat-oss#59]
https://github.com/jeromerobert/hmat-oss/blob/master/src/disable_threading.cpp#L75

I can't find which include file defines it.

```
--- CMakeFiles/hmat-oss.dir/src/disable_threading.cpp.o ---
/usr/ports/math/hmat-oss/work/hmat-oss-1.5.0-340-g700d1fa/src/disable_threading.cpp:59:5: error: use of undeclared identifier 'openblas_set_num_threads'; did you mean 'omp_set_num_threads'?
    openblas_set_num_threads(1);
    ^~~~~~~~~~~~~~~~~~~~~~~~
    omp_set_num_threads
/usr/local/include/omp.h:54:42: note: 'omp_set_num_threads' declared here
    extern void   __KAI_KMPC_CONVENTION  omp_set_num_threads (int);
                                         ^
```

**Comment by yurivict** [comment]
FreeBSD 11.2 amd64
openblas-0.2.20_7,1

**Comment by jeromerobert** [comment]
https://github.com/xianyi/OpenBLAS/blob/v0.2.20/cblas.h#L13

**Comment by yurivict** [comment]
Somehow ```openblas_set_num_threads``` is missing in the older version of ```openblas``` on FreeBSD, and it can't be easily updated at this time.

As a workaround, I undefined ```OPENBLAS_DISABLE_THREADS``` in ```config.h```.
