### ISSUE TITLE
warning: argument unused during compilation: '-L/usr/local/lib'

### ISSUE THREAD

**Issue by yurivict** [jeromerobert/hmat-oss#60]
clang-6 prints a lot of these warnings.

There is no need to supply library directories to a compiler.

**Comment by jeromerobert** [comment]
I need more informations

**Comment by yurivict** [comment]
Please remove all ```-Lxxx``` from the compile lines.

**Comment by jeromerobert** [comment]
I did not added any -Lxxx to the compiles lines.

**Comment by jeromerobert** [comment]
You should search for CMakeCache.txt and all CMake files to find from where this `-L/usr/loca/lib` comes from.
