### ISSUE TITLE
examples/kriging.cpp includes headers that are not installed

### ISSUE THREAD

**Issue by pgrt** [jeromerobert/hmat-oss#79]
Hello,

I am currently upgrading hmat-oss in Debian.

I noticed all the provided examples run fine, except kriging.cpp which requires headers in src/. Yet those header files are not installed. Would you expect it to run after your library is setup on a computer?

Best wishes,
Pierre

**Comment by jeromerobert** [comment]
This examples was written in a time we expected to have a C++ API. It's not the case anymore, so I just removed it. Thank you.
