### ISSUE TITLE
Building against g++14

### ISSUE THREAD

**Issue by pgrt** [jeromerobert/hmat-oss#95]
Hello,

I am the Debian maintainer of hmat-oss.

Within this year, g++14 will become the default in Debian. We saw that hmat-oss 1.8.1 and 1.9.0 fail to build against it: see build log
  https://qa-logs.debian.net/2024/07/01/hmat-oss_1.8.1-2_unstable_gccexp.log

I used the attached patch to manage the build -- which runs fine now. It would be cool if you had the opportunity to review it.

Best wishes,

Pierre

[g++14.txt](https://github.com/user-attachments/files/16156978/g%2B%2B14.txt)

**Comment by jeromerobert** [comment]
It's already there: 672ba6ecea4156b207f36e851608cf7467464e59

I will tag a new version.

**Comment by pgrt** [comment]
Hello,

Thanks! And apologies, I admit I overlooked it.

Best regards,

Pierre
